name: aucsy
description: NFT Action Mobile Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  shared_preferences: ^2.1.0
  flutter_svg: ^2.0.5
  phlox_animations: ^2.1.1
  visibility_detector: ^0.4.0+2
  flutter_staggered_animations: ^1.1.1
  sms_autofill: ^2.3.0
  pinput: ^2.2.31
  get: ^4.6.5
  cached_network_image: ^3.2.3
  http: ^0.13.6
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
